//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_B2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public int ID { get; set; }
        public string TenBaiViet { get; set; }
        public string LoaiBaiViet { get; set; }
        public string TieuDe { get; set; }
        public string NoiDungChiTiet { get; set; }
    }
}
